//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        public int IdHistorial { get; set; }
        public int Numero { get; set; }
        public int Resultado { get; set; }
        public System.DateTime FechaHora { get; set; }
    }
}
